version: '3.9'

services:
  web:
    container_name: skroub_web
    build:
      context: .
      dockerfile: src/docker/Dockerfile
    image: kamalesh1512/skroub:app
    ports:
      - '3000:3000'
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - app-net
    env_file:
      - .env.production
    command: ["npm", "run", "start"]

  worker:
    container_name: skroub_worker
    image: kamalesh1512/skroub:app
    restart: always
    environment:
      NODE_ENV: production
    env_file:
      - .env.production
    networks:
      - app-net
    command: ["tsx", "src/cron/scheduler.ts"]

networks:
  app-net:
    driver: bridge
